-- =========================================================
-- SISTEMA WEB DE APOYO ACADÉMICO PARA TUTORÍAS
-- Script de creación de tablas (PostgreSQL)
-- Base de datos: testdb
-- =========================================================

BEGIN;

-- =========================================================
-- Roles del sistema
-- =========================================================

CREATE TABLE roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(30) NOT NULL UNIQUE
);

-- =========================================================
-- Usuarios (tabla base para el login)
-- =========================================================

CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol INTEGER NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    contrasena_hash VARCHAR(255) NOT NULL,
    telefono VARCHAR(20),

    estado VARCHAR(10) NOT NULL DEFAULT 'activo'
        CHECK (estado IN ('activo', 'inactivo')),

    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol)
        REFERENCES roles(id_rol)
);

-- =========================================================
-- Carreras
-- =========================================================

CREATE TABLE carreras (
    id_carrera INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_carrera VARCHAR(150) NOT NULL
);

-- =========================================================
-- Estudiantes
-- =========================================================

CREATE TABLE estudiantes (
    id_estudiante INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL UNIQUE,
    id_carrera INTEGER NOT NULL,

    semestre SMALLINT NOT NULL,

    registro_universitario VARCHAR(30) UNIQUE,

    CONSTRAINT fk_estudiante_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario)
        ON DELETE CASCADE,

    CONSTRAINT fk_estudiante_carrera
        FOREIGN KEY (id_carrera)
        REFERENCES carreras(id_carrera)
);

-- =========================================================
-- Tutores
-- =========================================================

CREATE TABLE tutores (
    id_tutor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL UNIQUE,
    especialidad VARCHAR(150),
    biografia TEXT,

    CONSTRAINT fk_tutor_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario)
        ON DELETE CASCADE
);

-- =========================================================
-- Materias
-- =========================================================

CREATE TABLE materias (
    id_materia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_materia VARCHAR(150) NOT NULL,
    id_carrera INTEGER,

    CONSTRAINT fk_materia_carrera
        FOREIGN KEY (id_carrera)
        REFERENCES carreras(id_carrera)
);

-- =========================================================
-- Relación N:M tutor - materia
-- =========================================================

CREATE TABLE tutor_materia (
    id_tutor INTEGER NOT NULL,
    id_materia INTEGER NOT NULL,

    PRIMARY KEY (id_tutor, id_materia),

    CONSTRAINT fk_tutor_materia_tutor
        FOREIGN KEY (id_tutor)
        REFERENCES tutores(id_tutor)
        ON DELETE CASCADE,

    CONSTRAINT fk_tutor_materia_materia
        FOREIGN KEY (id_materia)
        REFERENCES materias(id_materia)
        ON DELETE CASCADE
);

-- =========================================================
-- Disponibilidad de tutores
-- =========================================================

CREATE TABLE disponibilidad_tutor (
    id_disponibilidad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tutor INTEGER NOT NULL,

    dia_semana VARCHAR(10) NOT NULL
        CHECK (
            dia_semana IN (
                'Lunes',
                'Martes',
                'Miercoles',
                'Jueves',
                'Viernes',
                'Sabado'
            )
        ),

    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,

    CONSTRAINT fk_disponibilidad_tutor
        FOREIGN KEY (id_tutor)
        REFERENCES tutores(id_tutor)
        ON DELETE CASCADE
);

-- =========================================================
-- Tutorías
-- =========================================================

CREATE TABLE tutorias (
    id_tutoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudiante INTEGER NOT NULL,
    id_tutor INTEGER NOT NULL,
    id_materia INTEGER NOT NULL,

    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,

    modalidad VARCHAR(10) NOT NULL DEFAULT 'presencial'
        CHECK (modalidad IN ('presencial', 'virtual')),

    lugar_o_enlace VARCHAR(200),

    estado VARCHAR(10) NOT NULL DEFAULT 'pendiente'
        CHECK (
            estado IN (
                'pendiente',
                'confirmada',
                'realizada',
                'cancelada'
            )
        ),

    observaciones TEXT,
    fecha_solicitud TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tutoria_estudiante
        FOREIGN KEY (id_estudiante)
        REFERENCES estudiantes(id_estudiante),

    CONSTRAINT fk_tutoria_tutor
        FOREIGN KEY (id_tutor)
        REFERENCES tutores(id_tutor),

    CONSTRAINT fk_tutoria_materia
        FOREIGN KEY (id_materia)
        REFERENCES materias(id_materia)
);

CREATE INDEX idx_tutoria_fecha
    ON tutorias(fecha);

CREATE INDEX idx_tutoria_estado
    ON tutorias(estado);

-- =========================================================
-- Evaluaciones de tutoría
-- =========================================================

CREATE TABLE evaluaciones_tutoria (
    id_evaluacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tutoria INTEGER NOT NULL UNIQUE,

    calificacion SMALLINT NOT NULL
        CHECK (calificacion BETWEEN 1 AND 5),

    comentario TEXT,
    fecha_evaluacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_evaluacion_tutoria
        FOREIGN KEY (id_tutoria)
        REFERENCES tutorias(id_tutoria)
        ON DELETE CASCADE
);

-- =========================================================
-- Registro de accesos
-- =========================================================

CREATE TABLE registro_accesos (
    id_acceso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,

    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_origen VARCHAR(45),

    resultado VARCHAR(10) NOT NULL
        CHECK (resultado IN ('exitoso', 'fallido')),

    CONSTRAINT fk_acceso_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario)
);

-- =========================================================
-- Datos semilla
-- =========================================================

INSERT INTO roles (nombre_rol)
VALUES
    ('administrador'),
    ('tutor'),
    ('estudiante');

INSERT INTO carreras (nombre_carrera)
VALUES
    ('Ingeniería de Sistemas');

-- IMPORTANTE:
-- Reemplazar el hash de ejemplo con uno generado mediante
-- password_hash() de PHP.

INSERT INTO usuarios (
    id_rol,
    nombre,
    apellido,
    correo,
    usuario,
    contrasena_hash
)
VALUES (
    1,
    'Admin',
    'Sistema',
    'admin@tutorias.local',
    'admin',
    '$2y$10$flRMKN6H63SI8vlKU9Pq5.M1yWQjb65CwjrEVOFE1CKwXxUJRFHJ6'
);

INSERT INTO materias (nombre_materia, id_carrera)
VALUES
    ('Base de Datos I', 1),
    ('Programación I', 1),
    ('Tecnología Web I', 1);

COMMIT;
